<a href="https://colab.research.google.com/github/BrianM50/MAT-421/blob/main/Module_D_Section_1_1%2C_1_2%2C_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sympy
import math

**Section 1.1(Introduction)**

Linear algebra is a field of mathematics that plays an important part in machine learning and data science. It includes topics such as data science and which includes vector spaces, orthogonality, eigenvalues, matrix decomposition and further expanded to include linear regression and principal component analysis.

In [ ]:
A = [1,2,3,4,5]
vectorA = np.array(A)
print('Row vector')
print(vectorA)
B = vectorA*2
print('Vector mulitplied by a scalar: ')
print(vectorA,"* 2 =",B)
print('')
mA = np.array([[2,1],[-1,0]])
print('Matrix')
print(mA)

Row vector
[1 2 3 4 5]
Vector mulitplied by a scalar: 
[1 2 3 4 5] * 2 = [ 2  4  6  8 10]

Matrix
[[ 2  1]
 [-1  0]]


**Section 1.2(Elements of Linear Algebra)**


In [ ]:
print('A linear combination is a new vector constructed from a subset by multiplying each vector and adding the results. \n')
print('Example:')
a = np.array([[1,2,3]])
b = np.array([[3,2,1]])
c = np.array([[2,1,3]])
print('a = ',a,'b = ', b,'c = ', c, '\n')
print('Linear Combination:')
print('2a + 3b + 2c')
d = 2*a + 3*b +2*c
print(d)

A linear combination is a new vector constructed from a subset by multiplying each vector and adding the results. 

Example:
a =  [[1 2 3]] b =  [[3 2 1]] c =  [[2 1 3]] 

Linear Combination:
2a + 3b + 2c
[[15 12 15]]


In [ ]:
print('A span is a set S of vectors which are the set of linear combinations of vectors in S. \n')
print('Example:')
e = np.array([[4,3]])
f = np.array([[1,2]])
print('e = ', e,  '\nf = ', f)
print('y = 2e + 3f')
y = 2*e + 3*f
print('y =', y)
print('The vectors e, f, and y are all part of the span, R^2.')

A span is a set S of vectors which are the set of linear combinations of vectors in S. 

Example:
e =  [[4 3]] 
f =  [[1 2]]
y = 2e + 3f
y = [[11 12]]
The vectors e, f, and y are all part of the span, R^2.


In [ ]:
print('Linear Independence occurs when a list of vectors cannot be written as a linear combinations of one another. \n')
print('Example:')
g = np.array([4,5])
h = np.array([2,1])
print('g =', g, '\nh =', h)
print('The vectors g and h are linearly independent because they are not multiples of each other (linear combinations). \n')

print('A list of vectors is linear dependent if it can be written as linear combination of the others. \n')
print('Example:')
i = np.array([1,3])
j = np.array([3,6])
print('i =', i, '\nj=',j)
print('Vectors i and j are linearly dependent because they are multiples of one another.')

Linear Independence occurs when a list of vectors cannot be written as a linear combinations of one another. 

Example:
g = [4 5] 
h = [2 1]
The vectors g and h are linearly independent because they are not multiples of each other (linear combinations). 

A list of vectors is linear dependent if it can be written as linear combination of the others. 

Example:
i = [1 3] 
j= [3 6]
Vectors i and j are linearly dependent because they are multiples of one another.


In [ ]:
print('Orthogonality is when two vectors are perpendicular to each other. This can be computed by using a dot product. If the dot product equals zero the two vectors are perpendicular. \n')
print('Example: ')
k = np.array([-6,2,])
l = np.array([2,6])
print('k =', k,'\nl =',l)
print('k*l =', np.dot(k,l))
print('The dot product of k and l is zero, which means the two vectors are perpendicular to each other and orthogonal.')

Orthogonality is when two vectors are perpendicular to each other. This can be computed by using a dot product. If the dot product equals zero the two vectors are perpendicular. 

Example: 
k = [-6  2] 
l = [2 6]
k*l = 0
The dot product of k and l is zero, which means the two vectors are perpendicular to each other and orthogonal.


In [ ]:
print('The Gram-Schmidt process is used to convert linearly independent vectors into an orthogonal basis \n')
print('Example:')
x1 = np.array([1,1,0])
x2 = np.array([-2,0,1])
print('Vectors x1 and x2 are linearly independent vectors')
print('x1 =',x1,'\nx2 =',x2)
v1 = x1/np.linalg.norm(x1)
v2 = x2 - ((np.dot(x2,x1))/np.dot(x1,x1))*x1
vo2 = v2/np.linalg.norm(v2)
print('We find the orthogonal basis to be')
print('v1 =',v1,'\nv2 =', vo2)

The Gram-Schmidt process is used to convert linearly independent vectors into an orthogonal basis 

Example:
Vectors x1 and x2 are linearly independent vectors
x1 = [1 1 0] 
x2 = [-2  0  1]
We find the orthogonal basis to be
v1 = [0.70710678 0.70710678 0.        ] 
v2 = [-0.57735027  0.57735027  0.57735027]


**Section 1.3(Linear Regression)**

In [ ]:
print("QR decomposition is used to solve the linear least squares problem. Using the Gram-Schmidt process we break down Matrix so that A = QR, where Q is an orthnormal matrix and R is an upper triangular matrix R.")
A = np.array([[20,15,30],[15,50,48],[5,24,6]], dtype = float)
print("Matrix A")
print(A)
x1 = np.array([20,15,5])
x2 = np.array([15,50,24])
x3 = np.array([30,48,6])
print('x1 =',x1,'\nx2 =', x2,'\nx3 =', x3)
v1 = x1/np.linalg.norm(x1)
v2 = x2 - ((np.dot(x2,x1))/np.dot(x1,x1))*x1
vo2 = v2/np.linalg.norm(v2)
v3 = x3 - (((np.dot(x3,x1))/np.dot(x1,x1))*x1) - (((np.dot(x3,v2))/np.dot(v2,v2))*v2)
vo3 = v3/np.linalg.norm(v3)
print('')
print('We find the orthnormal basis to be')
print('v1 =', v1, '\nv2 =', vo2,'\nv3 =', vo3)
print('')
print('The Matrix Q will then be')
Qtranspose = np.array([[v1],[vo2],[vo3]])
Q = Qtranspose.transpose()
print(Q)
print('')
print('To find R we need to multiply the transpose of Q by A, Q^(T)A = R')
r = np.dot(Qtranspose, A)
R = np.rint(r)
print('R =')
print(R)

QR decomposition is used to solve the linear least squares problem. Using the Gram-Schmidt process we break down Matrix so that A = QR, where Q is an orthnormal matrix and R is an upper triangular matrix R.
Matrix A
[[20. 15. 30.]
 [15. 50. 48.]
 [ 5. 24.  6.]]
x1 = [20 15  5] 
x2 = [15 50 24] 
x3 = [30 48  6]

We find the orthnormal basis to be
v1 = [0.78446454 0.58834841 0.19611614] 
v2 = [-0.6074847   0.66534038  0.43391764] 
v3 = [-0.12481077  0.45953055 -0.87934859]

The Matrix Q will then be
[[[ 0.78446454 -0.6074847  -0.12481077]]

 [[ 0.58834841  0.66534038  0.45953055]]

 [[ 0.19611614  0.43391764 -0.87934859]]]

To find R we need to multiply the transpose of Q by A, Q^(T)A = R
R =
[[[25. 46. 53.]]

 [[ 0. 35. 16.]]

 [[-0. -0. 13.]]]


In [ ]:
print('The least-squares problems involves solving for the system Ax = b, where A is a nxm matrix. Since matrix A is not a square matrix we have to use QR decomposition to solve the system')
print('Ax = b')
print('QRx = b')
print('Rx = Q^(T)b')
print('x = R^(-1)Q^(T)b')
B = np.array([[0,1],[1, 3],[2, 1]], dtype = float)
print('')
print("Matrix A")
print(B)
y1 = np.array([0,1,2])
y2 = np.array([1,3,1])
print('y1 =',y1,'\ny2 =', y2)
print('')
ve1 = y1/np.linalg.norm(y1)
ve2 = y2 - ((np.dot(y2,y1))/np.dot(y1,y1))*y1
vec2 = ve2/np.linalg.norm(ve2)
print('We find the orthnormal basis to be')
print('v1 =', ve1, '\nv2 =', vec2)
Q = np.array([[0,(math.sqrt(6))/6],[(math.sqrt(5))/5,(math.sqrt(6))/3],[2*(math.sqrt(5))/5,-(math.sqrt(6))/6]])
print('')
print('The Matrix Q is')
print(Q)

print('')
R = np.dot(Q.transpose(),B)
print('The R matrix is')
print(np.rint(R))

print('')
print('Let vector b be')
b = np.array([[1],[5],[6]], dtype = float)
print(b)
print('')
print('Now that we have the matices Q and R we can solve for x using the system QRx = b')
Qt = Q.transpose()
Rinv = np.linalg.inv(R)
print('Q^(T) =')
print(Qt)
print('')
print('R^(-1) =')
print(Rinv)
print('')
Qb = np.dot(Qt,b)
x = np.dot(Rinv, Qb)
print('Plugging these matrices into the equation x = R^(-1)Q^(T)b, we get x =')
print(x)
print('')
print('To check this is the correct x we multiply the matrix A by x to get b, Ax = b')
vecb = np.dot(B,x)
print(np.rint(vecb))

The least-squares problems involves solving for the system Ax = b, where A is a nxm matrix. Since matrix A is not a square matrix we have to use QR decomposition to solve the system
Ax = b
QRx = b
Rx = Q^(T)b
x = R^(-1)Q^(T)b

Matrix A
[[0. 1.]
 [1. 3.]
 [2. 1.]]
y1 = [0 1 2] 
y2 = [1 3 1]

We find the orthnormal basis to be
v1 = [0.         0.4472136  0.89442719] 
v2 = [ 0.40824829  0.81649658 -0.40824829]

The Matrix Q is
[[ 0.          0.40824829]
 [ 0.4472136   0.81649658]
 [ 0.89442719 -0.40824829]]

The R matrix is
[[2. 2.]
 [0. 2.]]

Let vector b be
[[1.]
 [5.]
 [6.]]

Now that we have the matices Q and R we can solve for x using the system QRx = b
Q^(T) =
[[ 0.          0.4472136   0.89442719]
 [ 0.40824829  0.81649658 -0.40824829]]

R^(-1) =
[[ 0.4472136  -0.40824829]
 [ 0.          0.40824829]]

Plugging these matrices into the equation x = R^(-1)Q^(T)b, we get x =
[[2.56666667]
 [0.83333333]]

To check this is the correct x we multiply the matrix A by x to get b, Ax = b
[[1.